### ISSUE TITLE
IP white listing and Default SMSC_ID

### ISSUE THREAD

**Issue by robinc001** [kneodev/ksmppd#48]
Hi,

There is a field named connect_allow_ip in **smpp_user** table . Is that field for white listing the ip of smpp user? 

Also there is default_smsc field in smpp_user table. But messages are going via another smsc id when the service of default_smsc is dead. How can we prevent messages going via another smsc id other than default smsc.

**Comment by robinc001** [comment]
Hi,

Any updates??

**Comment by kneodev** [comment]
Please read documentation

https://github.com/kneodev/ksmppd/wiki/MySQL:-smpp_user-column-meanings

your bearerbox must have other SMSCs configured without allowed-smsc-id which is why you are having message delivered via other gateways, please consult kannel user guide for how to route inside bearerbox

**Comment by robinc001** [comment]
I have configured bearebox with allowed-smsc-id parameter. But still it is not working

**Comment by kneodev** [comment]
I believe you are making an error, if you wish you can post your kannel config here and we can check

**Comment by robinc001** [comment]
group = smsc
smsc = smpp
smsc-id = mysmsc
host = "myip"
port = "myport"
transceiver-mode = 1
smsc-username = "uname"
smsc-password = "passwd"
source-addr-ton = 5
source-addr-npi = 0
dest-addr-ton = 1
dest-addr-npi = 1
system-type = smpp
allowed-smsc-id = mysmsc

**Comment by robinc001** [comment]
any updates?
