### ISSUE TITLE
source based routing

### ISSUE THREAD

**Issue by coinhosting** [kneodev/ksmppd#90]
Hi,

can anyone help me to setup ksmppd as source based routing for outbond Traffic
like..

if source Sender id is "ABC" then process this via smsc1 or bind1
if source sender id is "xyz" then process this via smsc2 or bind2

thanks

Deepak

**Comment by ib1corp** [comment]
Hi, we were struggling with kannel and the open source smpp servers all these years.

Finally we have developed our own In-house SMPP Server fully built on node.js & nosql technology. It has a capacity of validating DND Numbers/Blacklist/Spam/Intelligent Routing/SenderId based routing etc and a benchmark tested validation speed of 25+ Lakh message validations per second. SMPP TPS is scale-able to several thousand TPS. If anyone is interested in enterprise grade smpp server with the ability to shed a high budget/price, please contact me "iwebpush" at gmail dot com

**Comment by dspasoski** [comment]
Struggling? How can you say that? 15+ years of kannel (a couple with ksmppd) and open source and we never looked back. While it’s easy to criticize shortcoming or bugs, it’s also easy to forget what it does for us on a day to day base. Please don’t use this
 list for commercial advertising. If you don’t like open source, don’t use it.


BR,
Davor


On Jun 24, 2018, at 3:00 PM, ib1corp <notifications@github.com> wrote:


Hi, we were struggling with kannel and the open source smpp servers all these years.
Finally we have developed our own In-house SMPP Server fully built on node.js & nosql technology. It has a capacity of validating DND Numbers/Blacklist/Spam/Intelligent Routing/SenderId based routing etc and a benchmark tested validation speed of
 25+ Lakh message validations per second. SMPP TPS is scale-able to several thousand TPS. If anyone is interested in enterprise grade smpp server with the ability to shed a high budget/price, please contact me "iwebpush" at gmail dot com
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.








Disclaimer: one.Vip DOOEL Skopje
This e-mail (including any attachments) is confidential and may be protected by legal privilege. If you are not the intended recipient, you should not copy it, re-transmit it, use it or disclose its contents, but should return it to the sender immediately and
 delete your copy from your system. Any unauthorized use or dissemination of this message in whole or in part is strictly prohibited. Please note that e-mails are susceptible to change. one.Vip DOOEL Skopje shall not be liable for the improper or incomplete
 transmission of the information contained in this communication nor for any delay in its receipt or damage to your system.
Please, do not print this e-mail unless it is necessary! Think about saving the environment!

Напомена: оне.Вип ДООЕЛ Скопје
Оваа електронска порака (вклучувајќи ги и прилозите) е доверлива и може да биде заштитена со правни привилегии. Доколку не сте лицето на кое таа му е наменета пораката, не треба да ја копирате, дистрибуирате или да ја откривате нејзината содржина, туку веднаш
 да ја препратите до испраќачот и да ја избришете оригиналната порака и сите нејзини копии од Вашиот компјутерски систем. Секое неовластено користење на оваа порака во целост или делови од истата е строго забрането. Ве молиме да забележите дека електронските
 пораки се подложни на промени. оне.Вип ДООЕЛ Скопје не презема одговорност за несоодветно или нецелосно пренесување на информациите содржани во оваа комуникација, ниту пак за било какво задоцнување на приемот или оштетувања на вашиот систем.
Ве молиме не ја печатете оваа порака освен ако не е неопходно! Зачувајте ја природата!

**Comment by coinhosting** [comment]
hi,

this works for me no need any help on this topic 

thanks
